import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Extracción de Seguidores (TikTok, Twitter, Facebook)\n",
    "\n",
    "Este notebook centraliza el scraping de seguidores de las tres redes sociales. Extrae la informaci\u00f3n desde el Excel original y guarda (o actualiza) los datos en un \u00fanico archivo maestro: esultados/seguidores.csv."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import nest_asyncio\n",
    "nest_asyncio.apply()\n",
    "\n",
    "import time\n",
    "import re\n",
    "import random\n",
    "import asyncio\n",
    "import requests\n",
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "from playwright.async_api import async_playwright, TimeoutError as PWTimeout\n",
    "\n",
    "# \u2500\u2500\u2500 CONFIGURACI\u00d3N GLOBAL \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
    "_SCRAPERS_DIR = Path().resolve()\n",
    "_HERRAMIENTAS_DIR = _SCRAPERS_DIR.parent\n",
    "_PROYECTO_DIR = _HERRAMIENTAS_DIR.parent\n",
    "_RESULTADOS_DIR = _HERRAMIENTAS_DIR / \"resultados\"\n",
    "_RESULTADOS_DIR.mkdir(exist_ok=True)\n",
    "\n",
    "INPUT_FILE = _PROYECTO_DIR / \"Colombia\" / \"Resultados electorales.xlsx\"\n",
    "SHEET_NAME = \"Redes Sociales\"\n",
    "OUTPUT_CSV = _RESULTADOS_DIR / \"seguidores.csv\"\n",
    "\n",
    "USER_AGENT = (\n",
    "    \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
    "    \"AppleWebKit/537.36 (KHTML, like Gecko) \"\n",
    "    \"Chrome/124.0.0.0 Safari/537.36\"\n",
    ")\n",
    "\n",
    "def cargar_maestro(df_excel):\n",
    "    if OUTPUT_CSV.exists():\n",
    "        df_final = pd.read_csv(OUTPUT_CSV, sep=\";\")\n",
    "    else:\n",
    "        df_final = df_excel[[\"ID Candidato\", \"Candidato\"]].copy()\n",
    "    return df_final\n",
    "\n",
    "def guardar_maestro(df_final):\n",
    "    df_final.to_csv(OUTPUT_CSV, index=False, encoding=\"utf-8-sig\", sep=\";\")\n",
    "    print(f\"\\n\\u2705 Archivo maestro actualizado en: {OUTPUT_CSV}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. TikTok"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_tiktok_username(tiktok_url: str):\n",
    "    if not tiktok_url or pd.isna(tiktok_url):\n",
    "        return None\n",
    "    match = re.search(r'tiktok\\.com/@([\\w.]+)', str(tiktok_url))\n",
    "    if match: return match.group(1)\n",
    "    return str(tiktok_url).strip('@').split('?')[0].strip('/')\n",
    "\n",
    "async def scrape_tiktok_html(username: str, context):\n",
    "    url = f\"https://tokcount.com/?user={username}\"\n",
    "    page = await context.new_page()\n",
    "    try:\n",
    "        await page.goto(url, timeout=30000, wait_until=\"domcontentloaded\")\n",
    "        await asyncio.sleep(2)\n",
    "        html = await page.content()\n",
    "        match = re.search(r'\"followers\":(\\d+)', html)\n",
    "        if match:\n",
    "            return int(match.group(1))\n",
    "        return None\n",
    "    except Exception as e:\n",
    "        print(f\"  Error con @{username}: {e}\")\n",
    "        return None\n",
    "    finally:\n",
    "        await page.close()\n",
    "\n",
    "async def procesar_tiktok():\n",
    "    print(f\"Leyendo listado base...\")\n",
    "    df_excel = pd.read_excel(INPUT_FILE, sheet_name=SHEET_NAME, engine=\"openpyxl\")\n",
    "    df_excel[\"tiktok_username\"] = df_excel[\"TikTok\"].apply(extract_tiktok_username)\n",
    "    candidatos = df_excel[df_excel[\"tiktok_username\"].notna() & (df_excel[\"tiktok_username\"] != \"\")]\n",
    "    \n",
    "    df_final = cargar_maestro(df_excel)\n",
    "    for col in [\"tiktok_username\", \"tiktok_followers\", \"tiktok_fecha_captura\"]:\n",
    "        if col not in df_final.columns: df_final[col] = None\n",
    "        else: df_final[col] = df_final[col].astype(object)\n",
    "            \n",
    "    fecha = pd.Timestamp.now().strftime(\"%Y-%m-%d %H:%M\")\n",
    "    total = len(candidatos)\n",
    "    print(f\"Iniciando TikTok ({total} cuentas)...\")\n",
    "\n",
    "    async with async_playwright() as p:\n",
    "        browser = await p.chromium.launch(headless=True)\n",
    "        context = await browser.new_context(user_agent=USER_AGENT, locale=\"es-CO\")\n",
    "        \n",
    "        for i, (_, row) in enumerate(candidatos.iterrows(), 1):\n",
    "            username = row['tiktok_username']\n",
    "            id_cand = row['ID Candidato']\n",
    "            print(f\"[{i:3d}/{total}] @{username:<30} \u2192 \", end=\"\", flush=True)\n",
    "            \n",
    "            followers = await scrape_tiktok_html(username, context)\n",
    "            idx = df_final[df_final[\"ID Candidato\"] == id_cand].index\n",
    "            if idx.empty:\n",
    "                df_final = pd.concat([df_final, pd.DataFrame([{\"ID Candidato\": id_cand, \"Candidato\": row[\"Candidato\"]}])], ignore_index=True)\n",
    "                idx = [len(df_final) - 1]\n",
    "                \n",
    "            df_final.loc[idx[0], \"tiktok_username\"] = username\n",
    "            if followers is not None:\n",
    "                df_final.loc[idx[0], \"tiktok_followers\"] = followers\n",
    "                df_final.loc[idx[0], \"tiktok_fecha_captura\"] = fecha\n",
    "                print(f\"{followers:,} [OK]\")\n",
    "            else:\n",
    "                print(\"No encontrado [X]\")\n",
    "                \n",
    "            if i < total: await asyncio.sleep(random.uniform(3, 6))\n",
    "        await browser.close()\n",
    "        \n",
    "    guardar_maestro(df_final)\n",
    "\n",
    "# Descomenta la siguiente linea para ejecutar TikTok\n",
    "# await procesar_tiktok()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Twitter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_twitter_username(twitter_url: str):\n",
    "    if not twitter_url or pd.isna(twitter_url): return None\n",
    "    s = str(twitter_url).strip()\n",
    "    if not s.startswith(\"http\"): return s.lstrip(\"@\").split(\"/\")[0].strip() or None\n",
    "    match = re.search(r'(?:twitter\\.com|x\\.com)/([A-Za-z0-9_]+)', s)\n",
    "    return match.group(1) if match else None\n",
    "\n",
    "def parse_tw_followers(text: str):\n",
    "    if not text: return None\n",
    "    clean = text.strip().replace(\" \", \"\")\n",
    "    if \",\" in clean and \".\" in clean:\n",
    "        clean = clean.replace(\",\", \"\") if clean.rfind(\".\") > clean.rfind(\",\") else clean.replace(\".\", \"\")\n",
    "        clean = clean.split(\".\")[0] if \".\" in clean else clean.split(\",\")[0]\n",
    "    elif \".\" in clean:\n",
    "        parts = clean.split(\".\")\n",
    "        clean = clean.replace(\".\", \"\") if all(len(p) == 3 for p in parts[1:]) else parts[0]\n",
    "    elif \",\" in clean: clean = clean.replace(\",\", \"\")\n",
    "    try: return int(clean)\n",
    "    except: return None\n",
    "\n",
    "async def scrape_twitter_circleboom(page, username: str):\n",
    "    try:\n",
    "        await page.goto(\"https://circleboom.com/live-twitter-follower-counter\", timeout=25000, wait_until=\"domcontentloaded\")\n",
    "        await asyncio.sleep(2)\n",
    "        search = page.locator(\"#search\")\n",
    "        await search.wait_for(timeout=10000)\n",
    "        await search.click()\n",
    "        await search.evaluate(\"node => node.select()\")\n",
    "        await search.fill(username)\n",
    "        await page.locator(\"button.content_search_btn__VRDNS\").first.click()\n",
    "        \n",
    "        res_sel = \"div.content_searched_user_id__fYj_P span\"\n",
    "        try: await page.wait_for_selector(res_sel, timeout=8000)\n",
    "        except PWTimeout: await asyncio.sleep(8)\n",
    "        \n",
    "        raw = await page.locator(res_sel).first.inner_text()\n",
    "        return parse_tw_followers(raw)\n",
    "    except Exception as e:\n",
    "        return None\n",
    "\n",
    "async def procesar_twitter():\n",
    "    print(f\"Leyendo listado base...\")\n",
    "    df_excel = pd.read_excel(INPUT_FILE, sheet_name=SHEET_NAME, engine=\"openpyxl\")\n",
    "    df_excel[\"twitter_username\"] = df_excel[\"X / Twitter\"].apply(extract_twitter_username)\n",
    "    candidatos = df_excel[df_excel[\"twitter_username\"].notna() & (df_excel[\"twitter_username\"] != \"\")]\n",
    "    \n",
    "    df_final = cargar_maestro(df_excel)\n",
    "    for col in [\"twitter_username\", \"twitter_followers\", \"twitter_fecha_captura\"]:\n",
    "        if col not in df_final.columns: df_final[col] = None\n",
    "        else: df_final[col] = df_final[col].astype(object)\n",
    "\n",
    "    fecha = pd.Timestamp.now().strftime(\"%Y-%m-%d %H:%M\")\n",
    "    total = len(candidatos)\n",
    "    print(f\"Iniciando Twitter ({total} cuentas)...\")\n",
    "\n",
    "    async with async_playwright() as p:\n",
    "        browser = await p.chromium.launch(headless=True)\n",
    "        context = await browser.new_context(user_agent=USER_AGENT, locale=\"en-US\")\n",
    "        page = await context.new_page()\n",
    "        \n",
    "        for i, (_, row) in enumerate(candidatos.iterrows(), 1):\n",
    "            username = row['twitter_username']\n",
    "            id_cand = row['ID Candidato']\n",
    "            print(f\"[{i:3d}/{total}] @{username:<30} \u2192 \", end=\"\", flush=True)\n",
    "            \n",
    "            followers = await scrape_twitter_circleboom(page, username)\n",
    "            idx = df_final[df_final[\"ID Candidato\"] == id_cand].index\n",
    "            if idx.empty:\n",
    "                df_final = pd.concat([df_final, pd.DataFrame([{\"ID Candidato\": id_cand, \"Candidato\": row[\"Candidato\"]}])], ignore_index=True)\n",
    "                idx = [len(df_final) - 1]\n",
    "                \n",
    "            df_final.loc[idx[0], \"twitter_username\"] = username\n",
    "            if followers is not None:\n",
    "                df_final.loc[idx[0], \"twitter_followers\"] = followers\n",
    "                df_final.loc[idx[0], \"twitter_fecha_captura\"] = fecha\n",
    "                print(f\"{followers:,} [OK]\")\n",
    "            else:\n",
    "                print(\"No encontrado [X]\")\n",
    "                \n",
    "            if i < total: await asyncio.sleep(random.uniform(5, 10))\n",
    "        await browser.close()\n",
    "        \n",
    "    guardar_maestro(df_final)\n",
    "\n",
    "# Descomenta la siguiente linea para ejecutar Twitter\n",
    "# await procesar_twitter()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Facebook"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "APIFY_TOKEN = \"apify_api_EVQ13mkGT4eoE73NpplJhzZw6KWOLc1uParr\"\n",
    "ACTOR_ID    = \"alpha-scraper~facebook-page-followers-following-count-scraper\"\n",
    "\n",
    "def extract_fb_username(fb_url: str):\n",
    "    if pd.isna(fb_url): return None\n",
    "    s = str(fb_url).strip()\n",
    "    if not s.startswith(\"http\") and \"facebook.com\" not in s: return s.strip(\"/\")\n",
    "    if \"profile.php\" in s: return None\n",
    "    match = re.search(r'facebook\\.com/([A-Za-z0-9._-]+)', s)\n",
    "    if match:\n",
    "        name = match.group(1)\n",
    "        if name.lower() not in {\"pages\", \"groups\", \"events\", \"watch\", \"login\", \"sharer\", \"profile.php\"}:\n",
    "            return name\n",
    "    return None\n",
    "\n",
    "def parse_fb_count(value):\n",
    "    if value is None or str(value).strip() == \"N/A\": return None\n",
    "    if isinstance(value, (int, float)): return int(value)\n",
    "    s = str(value).strip().upper().replace(\" \", \"\")\n",
    "    for suffix, mult in {\"K\": 1_000, \"M\": 1_000_000, \"B\": 1_000_000_000}.items():\n",
    "        if s.endswith(suffix):\n",
    "            try: return int(float(s[:-1]) * mult)\n",
    "            except: return None\n",
    "    try: return int(s.replace(\",\", \"\").replace(\".\", \"\"))\n",
    "    except: return None\n",
    "\n",
    "def process_fb_batch(usernames: list):\n",
    "    url_runs = f\"https://api.apify.com/v2/acts/{ACTOR_ID}/runs\"\n",
    "    headers = {\"Content-Type\": \"application/json\"}\n",
    "    params = {\"token\": APIFY_TOKEN}\n",
    "    \n",
    "    resp = requests.post(url_runs, json={\"usernames\": usernames}, headers=headers, params=params)\n",
    "    if resp.status_code not in (200, 201): return {u: None for u in usernames}\n",
    "    \n",
    "    run_id = resp.json()[\"data\"][\"id\"]\n",
    "    elapsed = 0\n",
    "    success = False\n",
    "    while elapsed < 300:\n",
    "        st = requests.get(f\"https://api.apify.com/v2/actor-runs/{run_id}\", params=params).json().get(\"data\", {}).get(\"status\", \"\")\n",
    "        if st == \"SUCCEEDED\":\n",
    "            success = True\n",
    "            break\n",
    "        if st in (\"FAILED\", \"ABORTED\", \"TIMED-OUT\"): break\n",
    "        time.sleep(5)\n",
    "        elapsed += 5\n",
    "        \n",
    "    results = {u: None for u in usernames}\n",
    "    if success:\n",
    "        items = requests.get(f\"https://api.apify.com/v2/actor-runs/{run_id}/dataset/items\", params={\"token\": APIFY_TOKEN, \"format\": \"json\"}).json()\n",
    "        for item in items:\n",
    "            uname = item.get(\"page_username\") or item.get(\"username\") or item.get(\"pageUsername\")\n",
    "            folls = item.get(\"followers_count\") or item.get(\"followersCount\") or item.get(\"followers\")\n",
    "            if uname and uname in results: results[uname] = parse_fb_count(folls)\n",
    "    return results\n",
    "\n",
    "def procesar_facebook():\n",
    "    print(f\"Leyendo listado base...\")\n",
    "    df_excel = pd.read_excel(INPUT_FILE, sheet_name=SHEET_NAME, engine=\"openpyxl\")\n",
    "    df_excel[\"fb_username\"] = df_excel[\"Facebook\"].apply(extract_fb_username)\n",
    "    candidatos = df_excel[df_excel[\"fb_username\"].notna() & (df_excel[\"fb_username\"] != \"\")]\n",
    "    unicos = candidatos[\"fb_username\"].unique().tolist()\n",
    "    \n",
    "    df_final = cargar_maestro(df_excel)\n",
    "    for col in [\"facebook_username\", \"facebook_followers\", \"facebook_fecha_captura\"]:\n",
    "        if col not in df_final.columns: df_final[col] = None\n",
    "        else: df_final[col] = df_final[col].astype(object)\n",
    "\n",
    "    fecha = pd.Timestamp.now().strftime(\"%Y-%m-%d %H:%M\")\n",
    "    batch_size = 10\n",
    "    batches = [unicos[i: i + batch_size] for i in range(0, len(unicos), batch_size)]\n",
    "    print(f\"Iniciando Facebook ({len(unicos)} cuentas en {len(batches)} lotes)...\")\n",
    "\n",
    "    todos_resultados = {}\n",
    "    for i, b in enumerate(batches, 1):\n",
    "        print(f\"\\nLote {i}/{len(batches)}...\")\n",
    "        res = process_fb_batch(b)\n",
    "        todos_resultados.update(res)\n",
    "        for u, f in res.items():\n",
    "            print(f\"   @{u:<30} \u2192 {f'{f:,} [OK]' if f is not None else 'No encontrado [X]'}\")\n",
    "        if i < len(batches): time.sleep(3)\n",
    "\n",
    "    for _, row in candidatos.iterrows():\n",
    "        username = row[\"fb_username\"]\n",
    "        id_cand = row[\"ID Candidato\"]\n",
    "        followers = todos_resultados.get(username)\n",
    "        \n",
    "        idx = df_final[df_final[\"ID Candidato\"] == id_cand].index\n",
    "        if idx.empty:\n",
    "            df_final = pd.concat([df_final, pd.DataFrame([{\"ID Candidato\": id_cand, \"Candidato\": row[\"Candidato\"]}])], ignore_index=True)\n",
    "            idx = [len(df_final) - 1]\n",
    "            \n",
    "        df_final.loc[idx[0], \"facebook_username\"] = username\n",
    "        if followers is not None:\n",
    "            df_final.loc[idx[0], \"facebook_followers\"] = followers\n",
    "            df_final.loc[idx[0], \"facebook_fecha_captura\"] = fecha\n",
    "\n",
    "    guardar_maestro(df_final)\n",
    "\n",
    "# Descomenta la siguiente linea para ejecutar Facebook\n",
    "# procesar_facebook()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("Herramientas/scrapers/seguidores.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
